In [2]:
import numpy as np
import sys

In [3]:
a = np.array([1,2,3],dtype = 'int32')
print (a)

[1 2 3]


In [4]:
b=np.array([[1,2,3,8],[3,1,5,6]])
print(b)

[[1 2 3 8]
 [3 1 5 6]]


In [5]:
c = np.array([[[1,2,3],[5,7,8],[9,7,4]]])
print(c)


[[[1 2 3]
  [5 7 8]
  [9 7 4]]]


In [6]:
#getting dimensions of your numpy array
a.ndim

1

In [7]:
#get shape
a.shape
# b.shape

(3,)

In [8]:
#get data type
a.dtype

dtype('int32')

In [9]:
#get size
a.itemsize

4

In [10]:
#get total size
value = a.size * a.itemsize
print(value)

12


# Acessing /changing specific elements,rows , columns etc

In [11]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
#accessing the elements from row and column index
a[1,3]

9

In [13]:
#get  a specific row 
a[0,:]

array([1, 2, 3, 4, 5])

In [14]:
#get a specific column
a[:, 4]


array([ 5, 10])

In [15]:
a[0, 1:3]

array([2, 3])

In [16]:
a[1,3]=10
print(a)

a[:,2]=5
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8 10 10]]
[[ 1  2  5  4  5]
 [ 6  7  5 10 10]]


# 3D example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
b[1,1,:]

array([7, 8])

In [19]:
#replacing the elements

b[1,:,:]=[[4,5],[9,10]]
print (b)

[[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [ 9 10]]]


# Initializing different types of array

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((4,2,2), dtype = 'int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [22]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [23]:
# Random decimal numbers

np.random.rand(4,2)

array([[0.42809059, 0.11510253],
       [0.59882211, 0.42924104],
       [0.57584604, 0.2283152 ],
       [0.10074355, 0.63702565]])

In [24]:
# Random integer values
np.random.randint(4,7, size=(3,3))


array([[4, 6, 5],
       [4, 4, 6],
       [6, 6, 6]])

In [25]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
#repeating array

arr = np.array([1,2,3])
r1 = np.repeat(arr,2)
print(r1)

[1 1 2 2 3 3]


In [27]:
ones = np.ones((5,5))
print (ones)

z = np.zeros((3,3))
z[1,1]=9
print(z)

ones[1:4, 1:4] = z
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Make sure you copy the array using the array method

In [28]:
a = np.array([1,2,3])
b = a.copy()
print (b)
b[0]=100
print (b)
print (a)

[1 2 3]
[100   2   3]
[1 2 3]


# Mathematics

In [29]:
a= np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a *2

array([2, 4, 6, 8])

In [32]:
b = np.array([4,5,6,7])
a + b


array([ 5,  7,  9, 11])

In [34]:
# np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [35]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [36]:
#finding the determinant of the identity matrix

c = np.identity(3)
np.linalg.det(c)


1.0

# Statics

In [37]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.min(stats)

1

In [40]:
np.max(stats, axis=0)

array([4, 5, 6])

In [41]:
np.sum(stats, axis =0)

array([5, 7, 9])

In [42]:
np.sum(stats, axis = 1)

array([ 6, 15])

# Reorganizing Arrays

In [44]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [46]:
# Vertical stack
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2,v1])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [49]:
#horizonatal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscallaneous

In [53]:
#load data from files

filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# Boolean masking and advanced indexing

In [54]:
filedata > 30

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [56]:
filedata[filedata >30]

array([196,  75,  34,  42,  33, 766,  75,  55,  33, 999,  78,  76,  88],
      dtype=int32)

In [57]:
# you can index with a list in numpy

In [60]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,7]]


array([2, 3, 8])